language: java
sudo: false
script: mvn clean install
jdk:
  - oraclejdk8
services:
  - cassandra

cache:
  directories:
  - $HOME/.m2
  
after_success:
  - bash <(curl -s https://codecov.io/bash)


  
