language: java

sudo: false

script: mvn clean install

jdk:
  - oraclejdk8

services:
  - cassandra

cache:
  directories:
  - $HOME/.m2

# safelist
branches:
  only:
  - master

after_success:



  
