language: java

sudo: false

install: mvn clean install -Dgpg.skip

jdk:
  - oraclejdk8

services:
  - cassandra

cache:
  directories:
  - $HOME/.m2

# safelist
branches:
  only:
  - master

after_success:
  - bash <(curl -s https://codecov.io/bash)

#Build notification messages , upun build status 
notifications: 
  email:
    recipients:
      - Zohar.Sacks@amdocs.com
      - Halfon.Tal@amdocs.com
      - elhay.efrat1@amdocs.com
      - SHALOMB@Amdocs.com
      - Tali.Grama@amdocs.com
      - liron.shtraichman@amdocs.com
      - Oren.Kleks@amdocs.com
      
